### ISSUE TITLE
Cannot install @angular-devkit/build-angular@next via npm

### ISSUE THREAD

**Issue by juergenzimmermann** [angular/angular-devkit-build-angular-builds#4]
When I try to invoke "npm i -D @angular-devkit/build-angular@next" I get the following error message. The log file is attached.
```
npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Zimmermann\npm-cache\_logs\2019-02-19T06_57_43_501Z-debug.log
PS C:\workspace\software-engineering\angular-mean> npm i -D @angular-devkit/build-angular@next
npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Zimmermann\npm-cache\_logs\2019-02-19T07_03_30_103Z-debug.log
```

[2019-02-19T07_03_30_103Z-debug.log](https://github.com/angular/angular-devkit-build-angular-builds/files/2878732/2019-02-19T07_03_30_103Z-debug.log)

**Comment by juergenzimmermann** [comment]
The issues is gone.

**Comment by chmerk** [comment]
I do have this problem with 'npm install @angular-devkit/build-angular' (also e.g. with '@0.802' or '@latest'):
npm ERR! Maximum call stack size exceeded

Any ideas? Can you reopen the ticket?
